### ISSUE TITLE
RoIe lacks idempotency

### ISSUE THREAD

**Issue by gthieleb** [linuxhq/ansible-role-systemd#1]
I currently use your roles with this variables:
```
# linuxhq.systemd
systemd_hostnamectl:
  hostname: "{{ inventory_hostname_short }}"
  location: FSN1-DC3
systemd_localectl:
  locale: LANG=en_US.UTF-8
  keymap: de
  x11_keymap: de
systemd_timedatectl:
  local_rtc: no
  ntp: yes
  timezone: Europe/Berlin
```

Result, is that every playbook run changes everything:

```
TASK [linuxhq.systemd : Attempting to apply systemd hostnamectl configurations] ***********************************************************************************************************************************
changed: [ax41.example.com] => (item=hostname)
changed: [ax41.example.com] => (item=location)

TASK [linuxhq.systemd : Attempting to apply systemd localectl configurations] *************************************************************************************************************************************
changed: [ax41.example.com] => (item=locale)
changed: [ax41.example.com] => (item=keymap)
changed: [ax41.example.com] => (item=x11_keymap)

TASK [linuxhq.systemd : Attempting to apply systemd timedatectl configurations] ***********************************************************************************************************************************
changed: [ax41.example.com] => (item=local_rtc)
changed: [ax41.example.com] => (item=ntp)
changed: [ax41.example.com] => (item=timezone)
```
